version: "2"
services:
  pokeapi-cache-app:
    container_name: pokeapi-cache-app
    restart: always
    build: .
    environment:
      - POKEAPI_MONGO_HOST: localhost
      - POKEAPI_MONGO_PORT: 27108
      - POKEAPI_MONGO_DB: poke
     ports:
      - "1234:1234"
   pokeapi-cache-mongo:
      container_name: pokeapi-cache-mongo
      restart: always
      image: mongo
      environment:
    volumes:
      - ./_data:/data/db
    ports:
      - "27108:27107"
