version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
  mongo:
    container_name: mongo
    restart: always
    image: mongo:3
    volumes:
      - ./_data:/data/db
    ports:
      - "27017:27107"