version: "2"
services:
  app:
    env_file: app.env
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
  mongo:
    env_file: mongo.env
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./_data:/data/db
    ports:
      - "27017:27107"